### ISSUE TITLE
Craft 3 support?

### ISSUE THREAD

**Issue by proximo7** [selvinortiz/craft.spamguard#15]
We're using your excellent spamguard on a number of our Craft sites. Wondering if there is an upgrade planned for Craft 3.

**Comment by selvinortiz** [comment]
@pioneerdesign I wasn't planning on upgrading it because there hasn't been much demand for that plugin. However, it wouldn't be a difficult plugin to migrate.

I'll think about migrating it and let you know when I have a time table.

**Comment by darith27** [comment]
+1 Yes, please this plugin-in is amazing and we would love to use it with all of our future Craft 3 projects.

**Comment by moniquesp** [comment]
I'm also interested in this plugin and would love to see it in Craft 3.

**Comment by selvinortiz** [comment]
Just wanted to let everyone know that I've started working on SpamGuard for Craft 3. Should be able to have it done in a couple of weeks if all goes well.

**Comment by monooso** [comment]
@selvinortiz Is [this](https://github.com/selvinortiz/craft-plugin-spamguard) the Craft 3 repository? The README still references Craft 2, but the CHANGELOG states that Craft 3 support was added in version 0.7.0.

**Comment by selvinortiz** [comment]
@monooso This is the Craft 2 compatible version of the plugin. For Craft 3, see https://github.com/selvinortiz/craft-plugin-spamguard

However, the Craft 3 version is not quite there yet.

**Comment by monooso** [comment]
@selvinortiz Ah, looking through that repo, it seems somewhat incomplete.

Do you have an update on the status of the Craft 3 work? No expectations, I just have a project which requires Akismet integration, and I don't want to roll my own if you're just about to release an update.

**Comment by monooso** [comment]
@selvinortiz  Sorry, our comments overlapped. Thanks for the update.

**Comment by selvinortiz** [comment]
@monooso I shooting for a release within 2 weeks.

**Comment by j-greig** [comment]
Would also love a Craft 3 version :)

**Comment by selvinortiz** [comment]
Thank you for reminding me to update this thread.

SpamGuard is now Shield (Craft 3) https://plugins.craftcms.com/shield
